### ISSUE TITLE
Add option to preserve body

### ISSUE THREAD

**Issue by jqnatividad** [svenstaro/upload-release-action#107]
Before https://github.com/svenstaro/upload-release-action/pull/106, the body was preserved even when overwrite is true.

Could this behavior be restored, perhaps, with the addition of another flag - `preservebody`?

**Comment by regevbr** [comment]
I think that the fix is to check if the body/name are not empty, and overwrite them only in that case, will that solve your case?

**Comment by regevbr** [comment]
see #108

**Comment by jqnatividad** [comment]
Thanks @regevbr for the quick reply. 

Actually, the fix in my case is to preserve non-empty body when `overwrite` is true, as I invoke upload-release-action several times after a release build various zip files for a release, and I would like to preserve the body across invocations for the same release.

**Comment by regevbr** [comment]
I believe that is what I did in the fix - if a release exists with a body, and the body in the current action run (not the one from the existing release) does not exist (i.e. empty), then do not override it. Or am I missing something here?

**Comment by svenstaro** [comment]
Version 2.6.1 is deployed with a fix thanks to @regevbr. Please check.

**Comment by ZheSun88** [comment]
Hi we are having the same issue as described here. we publish the release note first and then upload one more file in the asset list.

after reading the [doc here](https://github.com/svenstaro/upload-release-action#input-variables)
```
overwrite: If an asset with the same name already exists, overwrite it (Default: false).
``` 
the `overwrite` argument seems should only overwrite the file in the assets, instead of overwriting the release note body content. 

did i get some something wrong?

**Comment by regevbr** [comment]
Did you try the latest version 2.6.1 ?

**Comment by ZheSun88** [comment]
ah, seems the latest the version works for us.. 

Thanks.
